export const GETBOOKS_PROGRESS='GETBOOKS_PROGRESS';
export const GETBOOKS_SUCCESS='GETBOOKS_SUCCESS';
export const GETBOOKS_FAIL='GETBOOKS_FAIL';

export const GETCATEGORY_PROGRESS='GETCATEGORY_PROGRESS';
export const GETCATEGORY_SUCCESS='GETCATEGORY_SUCCESS';
export const GETCATEGORY_FAIL='GETCATEGORY_FAIL';
